global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: md-succ-ai
    static_configs:
      - targets: ['md-api:3000']
    metrics_path: /metrics
    scrape_interval: 10s
